'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'th' | 'en'

const translations = {
  th: {
    home: 'หน้าหลัก',
    login: 'เข้าสู่ระบบ',
    register: 'ลงทะเบียน',
    logout: 'ออกจากระบบ',
    language: 'ภาษา / Language',
    guest: 'ผู้ใช้ทั่วไป',
    admin: 'ผู้ดูแลระบบ',
    teacher: 'อาจารย์',
    student: 'นักศึกษา',
    landing_title: 'ระบบจองห้องประชุมและห้องเรียน',
    landing_subtitle: 'เลือกประเภทห้องที่ต้องการจอง ห้องประชุมจองได้ทันทีโดยไม่ต้องเข้าสู่ระบบ ห้องเรียนต้องเข้าสู่ระบบก่อน',
    meeting_rooms: 'ห้องประชุม',
    meeting_rooms_desc: 'จองห้องประชุมได้ทันทีโดยไม่ต้องเข้าสู่ระบบ',
    classrooms: 'ห้องเรียน',
    classrooms_desc: 'ต้องเข้าสู่ระบบก่อนจึงจะสามารถเข้าใช้งานและจองห้องเรียนได้',
    book_now: 'จองเลย',
    sign_in_now: 'เข้าสู่ระบบ',
    footer_text: 'ระบบจองห้องประชุมและห้องเรียน · สำหรับบุคลากรและนักศึกษา',
    login_title: 'Classroom & Meeting Room',
    login_subtitle: 'ลงชื่อเข้าใช้เพื่อจัดการห้อง การจอง และงานที่ได้รับมอบหมาย',
    email: 'อีเมล',
    password: 'รหัสผ่าน',
    or: 'หรือ',
    signin_loading: 'กำลังเข้าสู่ระบบ...',
    secure_login: 'เข้าสู่ระบบอย่างปลอดภัยผ่าน JWT Authentication',
    public_booking_title: 'จองห้องประชุม',
    public_booking_subtitle: 'เลือกห้องประชุมและกรอกข้อมูลเพื่อจองได้ทันที',
    select_meeting_room: 'เลือกห้องประชุม',
    booking_info: 'ข้อมูลการจอง',
    booking_title_label: 'หัวข้อการจอง',
    booking_title_placeholder: 'เช่น ประชุมทีมรายสัปดาห์',
    purpose_label: 'วัตถุประสงค์',
    purpose_placeholder: 'เลือกวัตถุประสงค์',
    purpose_meeting: 'ประชุม',
    purpose_event: 'จัดกิจกรรม',
    purpose_other: 'อื่นๆ',
    start_time: 'วัน-เวลาเริ่มต้น',
    end_time: 'วัน-เวลาสิ้นสุด',
    description_label: 'รายละเอียดเพิ่มเติม (ถ้ามี)',
    description_placeholder: 'เช่น อุปกรณ์ที่ต้องการ, จำนวนผู้เข้าร่วม, ฯลฯ',
    requester_section: 'ข้อมูลผู้จอง',
    requester_name: 'ชื่อ-นามสกุล',
    requester_email: 'อีเมล',
    requester_phone: 'เบอร์โทรศัพท์',
    submit_booking: 'ยืนยันการจอง',
    submitting_booking: 'กำลังส่ง...',
    booking_success_title: 'จองสำเร็จ!',
    booking_success_desc: 'คำขอจองของคุณถูกส่งแล้ว เจ้าหน้าที่จะตรวจสอบและแจ้งผลทางอีเมล',
    book_more: 'จองเพิ่ม',
    capacity_people: 'คน',
    floor_label: 'ชั้น',
    nav_overview: 'ภาพรวม',
    nav_management: 'การจัดการ',
    nav_academic: 'การเรียนการสอน',
    nav_student: 'ข้อมูลนักศึกษา',
    nav_account: 'บัญชีผู้ใช้',
    nav_dashboard: 'Dashboard',
    nav_community: 'ชุมชนการเรียนรู้',
    nav_calendar: 'ปฏิทิน',
    nav_rooms: 'ห้องเรียน/ห้องประชุม',
    nav_bookings: 'การจองห้อง',
    nav_users: 'ผู้ใช้งาน',
    nav_classrooms: 'ห้องเรียนวิชา',
    nav_assignments: 'งานที่มอบหมาย',
    nav_quests: 'เควสการเรียนรู้',
    nav_reward_requests: 'คำขอรางวัล',
    nav_attendance: 'การเข้าเรียน',
    nav_grades: 'คะแนนและเกรด',
    nav_my_dashboard: 'แดชบอร์ดของฉัน',
    nav_my_classrooms: 'ห้องเรียนของฉัน',
    nav_my_assignments: 'งานของฉัน',
    nav_leaderboard: 'ตารางคะแนน',
    nav_rewards: 'ร้านรางวัล',
    nav_notifications: 'การแจ้งเตือน',
    nav_badges: 'ตราเกียรติยศ',
    nav_profile: 'ข้อมูลส่วนตัว',
    nav_settings: 'ตั้งค่าระบบ',
    dashboard_title: 'Dashboard',
    dashboard_subtitle: 'ภาพรวมของระบบจองห้องและระบบการเรียนรู้',
    total_rooms: 'ห้องทั้งหมด',
    active_bookings: 'การจองห้อง',
    assignments: 'จำนวนงาน',
    students: 'นักศึกษา',
    quick_actions: 'เมนูลัด',
    new_booking: 'จองห้องใหม่',
    new_booking_desc: 'จองห้องเรียนหรือห้องประชุม',
    new_assignment: 'มอบหมายงานใหม่',
    new_assignment_desc: 'สร้างงานชิ้นใหม่ให้นักศึกษา',
    view_calendar: 'ปฏิทินการจอง',
    view_calendar_desc: 'ดูตารางเวลาการใช้ห้อง',
    // Common UI
    search: 'ค้นหา',
    search_placeholder: 'ค้นหา...',
    clear: 'ล้าง',
    cancel: 'ยกเลิก',
    save: 'บันทึก',
    saving: 'กำลังบันทึก...',
    delete: 'ลบ',
    deleting: 'กำลังลบ...',
    edit: 'แก้ไข',
    view: 'ดู',
    add: 'เพิ่ม',
    confirm: 'ยืนยัน',
    back: 'ย้อนกลับ',
    next: 'ถัดไป',
    previous: 'ก่อนหน้า',
    loading: 'กำลังโหลด...',
    no_results: 'ไม่พบข้อมูล',
    try_again: 'ลองใหม่อีกครั้ง',
    something_went_wrong: 'เกิดข้อผิดพลาด',
    page_not_found: 'ไม่พบหน้านี้',
    go_back_home: 'กลับหน้าหลัก',
    showing_results: 'แสดง',
    of: 'จาก',
    to: 'ถึง',
    results: 'รายการ',
    per_page: 'ต่อหน้า',
    all_status: 'ทุกสถานะ',
    // Status badge labels
    status_active: 'ใช้งาน',
    status_available: 'ว่าง',
    status_inactive: 'ไม่ใช้งาน',
    status_pending: 'รออนุมัติ',
    status_approved: 'อนุมัติแล้ว',
    status_rejected: 'ปฏิเสธ',
    status_draft: 'แบบร่าง',
    status_published: 'เผยแพร่',
    status_archived: 'เก็บถาวร',
    status_open: 'เปิด',
    status_closed: 'ปิด',
    status_cancelled: 'ยกเลิก',
    status_present: 'มาเรียน',
    status_late: 'มาสาย',
    status_leave: 'ลา',
    status_absent: 'ขาด',
    status_graded: 'ให้คะแนนแล้ว',
    status_submitted: 'ส่งแล้ว',
    status_maintenance: 'ซ่อมบำรุง',
    // Page titles
    rooms_title: 'ห้องเรียน / ห้องประชุม',
    rooms_subtitle: 'จัดการห้องเรียนและห้องประชุมในระบบ',
    rooms_add: 'เพิ่มห้อง',
    rooms_search: 'ค้นหาห้อง...',
    rooms_empty_title: 'ยังไม่มีห้อง',
    rooms_empty_message: 'เริ่มต้นโดยการเพิ่มห้องแรกของคุณ',
    bookings_title: 'การจองห้อง',
    bookings_subtitle: 'จัดการคำขอจองและตรวจสอบสถานะ',
    bookings_add: 'จองห้องใหม่',
    bookings_search: 'ค้นหาการจอง...',
    bookings_empty_title: 'ยังไม่มีการจอง',
    bookings_empty_message: 'เริ่มต้นโดยการจองห้องครั้งแรก',
    users_title: 'ผู้ใช้งาน',
    users_subtitle: 'จัดการผู้ใช้งานและบทบาทในระบบ',
    users_add: 'เพิ่มผู้ใช้',
    users_empty_title: 'ยังไม่มีผู้ใช้',
    users_empty_message: 'เพิ่มผู้ใช้คนแรกของคุณ',
    assignments_title: 'งานที่มอบหมาย',
    assignments_subtitle: 'จัดการงาน การบ้าน และคะแนน',
    assignments_add: 'มอบหมายงาน',
    assignments_search: 'ค้นหางาน...',
    assignments_empty_title: 'ยังไม่มีงาน',
    assignments_empty_message: 'เริ่มต้นโดยการมอบหมายงานชิ้นแรก',
    classrooms_title: 'ห้องเรียนของฉัน',
    classrooms_admin_subtitle: 'สร้างห้องเรียนและแบ่งปันรหัสเข้าชั้นกับนักศึกษา',
    classrooms_student_subtitle: 'เข้าร่วมชั้นเรียนและดูเนื้อหาจากอาจารย์',
    // Auth
    login_failed: 'เข้าสู่ระบบล้มเหลว กรุณาตรวจสอบข้อมูล',
    show_password: 'แสดงรหัสผ่าน',
    hide_password: 'ซ่อนรหัสผ่าน',
    register_title: 'สร้างบัญชีใหม่',
    register_subtitle: 'สมัครสมาชิกเพื่อเริ่มจัดการห้อง การจอง และงาน',
    full_name: 'ชื่อ-นามสกุล',
    full_name_placeholder: 'เช่น สมชาย ใจดี',
    confirm_password: 'ยืนยันรหัสผ่าน',
    confirm_password_placeholder: 'พิมพ์รหัสผ่านอีกครั้ง',
    password_placeholder: 'อย่างน้อย 6 ตัวอักษร',
    role_label: 'บทบาท',
    role_placeholder: 'เลือกบทบาท',
    teacher_invite_label: 'รหัสเชิญสำหรับอาจารย์',
    teacher_invite_placeholder: 'ป้อนรหัสเชิญที่ได้รับ',
    register_button: 'สมัครสมาชิก',
    creating_account: 'กำลังสร้างบัญชี...',
    account_created: 'สร้างบัญชีสำเร็จ!',
    redirecting: 'กำลังนำไปยังแดชบอร์ด...',
    have_account: 'มีบัญชีอยู่แล้ว?',
    signin_link: 'เข้าสู่ระบบที่นี่',
    passwords_do_not_match: 'รหัสผ่านไม่ตรงกัน',
    invalid_role: 'กรุณาเลือกบทบาทที่ถูกต้อง',
    teacher_invite_required: 'จำเป็นต้องระบุรหัสเชิญสำหรับอาจารย์',
    invalid_invite: 'รหัสเชิญไม่ถูกต้อง',
    email_exists: 'อีเมลนี้ถูกใช้งานแล้ว',
    register_failed: 'สมัครไม่สำเร็จ',
  },
  en: {
    home: 'Home',
    login: 'Sign In',
    register: 'Sign Up',
    logout: 'Sign Out',
    language: 'Language / ภาษา',
    guest: 'Guest',
    admin: 'Admin',
    teacher: 'Teacher',
    student: 'Student',
    landing_title: 'Room Booking System',
    landing_subtitle: 'Choose a room to book. Meeting rooms can be booked instantly without logging in. Classrooms require signing in first.',
    meeting_rooms: 'Meeting Rooms',
    meeting_rooms_desc: 'Reserve meeting rooms instantly without logging in.',
    classrooms: 'Classrooms',
    classrooms_desc: 'Sign in first to access classrooms and view courses.',
    book_now: 'Book Now',
    sign_in_now: 'Sign In',
    footer_text: 'Room Booking & Classroom Management System · For staff and students',
    login_title: 'Classroom & Meeting Room',
    login_subtitle: 'Sign in to manage rooms, bookings, and assignments',
    email: 'Email',
    password: 'Password',
    or: 'or',
    signin_loading: 'Signing in...',
    secure_login: 'Secure login powered by JWT authentication',
    public_booking_title: 'Book a Meeting Room',
    public_booking_subtitle: 'Choose a meeting room and fill in details to book instantly',
    select_meeting_room: 'Select a Meeting Room',
    booking_info: 'Booking Details',
    booking_title_label: 'Booking Title',
    booking_title_placeholder: 'e.g. Weekly team meeting',
    purpose_label: 'Purpose',
    purpose_placeholder: 'Select a purpose',
    purpose_meeting: 'Meeting',
    purpose_event: 'Event',
    purpose_other: 'Other',
    start_time: 'Start Time',
    end_time: 'End Time',
    description_label: 'Additional details (optional)',
    description_placeholder: 'e.g. required equipments, number of attendees, etc.',
    requester_section: 'Requester Details',
    requester_name: 'Full Name',
    requester_email: 'Email Address',
    requester_phone: 'Phone Number',
    submit_booking: 'Confirm Booking',
    submitting_booking: 'Submitting...',
    booking_success_title: 'Booking Confirmed!',
    booking_success_desc: 'Your booking request has been submitted. Officers will review and notify you via email.',
    book_more: 'Book More',
    capacity_people: 'people',
    floor_label: 'Floor',
    nav_overview: 'Overview',
    nav_management: 'Management',
    nav_academic: 'Academic',
    nav_student: 'Student Portal',
    nav_account: 'Account',
    nav_dashboard: 'Dashboard',
    nav_community: 'Community',
    nav_calendar: 'Calendar',
    nav_rooms: 'Rooms',
    nav_bookings: 'Bookings',
    nav_users: 'Users',
    nav_classrooms: 'Classrooms',
    nav_assignments: 'Assignments',
    nav_quests: 'Learning Quests',
    nav_reward_requests: 'Reward Requests',
    nav_attendance: 'Attendance',
    nav_grades: 'Grades',
    nav_my_dashboard: 'My Dashboard',
    nav_my_classrooms: 'My Classrooms',
    nav_my_assignments: 'My Assignments',
    nav_leaderboard: 'Leaderboard',
    nav_rewards: 'Reward Shop',
    nav_notifications: 'Notifications',
    nav_badges: 'Badges',
    nav_profile: 'Profile',
    nav_settings: 'Settings',
    dashboard_title: 'Dashboard',
    dashboard_subtitle: 'Overview of classroom and room management',
    total_rooms: 'Total Rooms',
    active_bookings: 'Active Bookings',
    assignments: 'Assignments',
    students: 'Students',
    quick_actions: 'Quick Actions',
    new_booking: 'New Booking',
    new_booking_desc: 'Book a room',
    new_assignment: 'New Assignment',
    new_assignment_desc: 'Create task',
    view_calendar: 'View Calendar',
    view_calendar_desc: 'See schedule',
    // Common UI
    search: 'Search',
    search_placeholder: 'Search...',
    clear: 'Clear',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving...',
    delete: 'Delete',
    deleting: 'Deleting...',
    edit: 'Edit',
    view: 'View',
    add: 'Add',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    loading: 'Loading...',
    no_results: 'No results',
    try_again: 'Try again',
    something_went_wrong: 'Something went wrong',
    page_not_found: 'Page not found',
    go_back_home: 'Go back home',
    showing_results: 'Showing',
    of: 'of',
    to: 'to',
    results: 'results',
    per_page: 'per page',
    all_status: 'All status',
    // Status badge labels
    status_active: 'Active',
    status_available: 'Available',
    status_inactive: 'Inactive',
    status_pending: 'Pending',
    status_approved: 'Approved',
    status_rejected: 'Rejected',
    status_draft: 'Draft',
    status_published: 'Published',
    status_archived: 'Archived',
    status_open: 'Open',
    status_closed: 'Closed',
    status_cancelled: 'Cancelled',
    status_present: 'Present',
    status_late: 'Late',
    status_leave: 'Leave',
    status_absent: 'Absent',
    status_graded: 'Graded',
    status_submitted: 'Submitted',
    status_maintenance: 'Maintenance',
    // Page titles
    rooms_title: 'Rooms',
    rooms_subtitle: 'Manage classrooms and meeting rooms',
    rooms_add: 'Add Room',
    rooms_search: 'Search rooms...',
    rooms_empty_title: 'No rooms yet',
    rooms_empty_message: 'Get started by adding your first room.',
    bookings_title: 'Bookings',
    bookings_subtitle: 'Manage room reservations and approvals',
    bookings_add: 'New Booking',
    bookings_search: 'Search bookings...',
    bookings_empty_title: 'No bookings yet',
    bookings_empty_message: 'Get started by creating your first booking.',
    users_title: 'Users',
    users_subtitle: 'Manage system users and roles',
    users_add: 'Add User',
    users_empty_title: 'No users yet',
    users_empty_message: 'Get started by adding your first user.',
    assignments_title: 'Assignments',
    assignments_subtitle: 'Manage class assignments, homework, and grades',
    assignments_add: 'Create Assignment',
    assignments_search: 'Search assignments...',
    assignments_empty_title: 'No assignments yet',
    assignments_empty_message: 'Get started by creating your first assignment.',
    classrooms_title: 'My Classrooms',
    classrooms_admin_subtitle: 'Create classrooms and share join codes with your students.',
    classrooms_student_subtitle: 'Join classes and view coursework from your teachers.',
    // Auth
    login_failed: 'Login failed. Please check your credentials.',
    show_password: 'Show password',
    hide_password: 'Hide password',
    register_title: 'Create Account',
    register_subtitle: 'Sign up to manage rooms, bookings, and assignments.',
    full_name: 'Full Name',
    full_name_placeholder: 'e.g. John Doe',
    confirm_password: 'Confirm Password',
    confirm_password_placeholder: 'Re-enter your password',
    password_placeholder: 'At least 6 characters',
    role_label: 'Role',
    role_placeholder: 'Select a role',
    teacher_invite_label: 'Teacher Invite Code',
    teacher_invite_placeholder: 'Enter your invite code',
    register_button: 'Sign Up',
    creating_account: 'Creating account...',
    account_created: 'Account created!',
    redirecting: 'Redirecting to dashboard...',
    have_account: 'Already have an account?',
    signin_link: 'Sign in here',
    passwords_do_not_match: 'Passwords do not match',
    invalid_role: 'Please choose a valid role',
    teacher_invite_required: 'Teacher invite code is required',
    invalid_invite: 'Invalid teacher invite code',
    email_exists: 'This email is already registered',
    register_failed: 'Registration failed',
  },
}

interface LanguageContextProps {
  lang: Language
  setLang: (lang: Language) => void
  t: (key: keyof typeof translations['th']) => string
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('th')

  useEffect(() => {
    const saved = localStorage.getItem('app-lang') as Language
    if (saved === 'th' || saved === 'en') {
      setLangState(saved)
    }
  }, [])

  const setLang = (newLang: Language) => {
    setLangState(newLang)
    localStorage.setItem('app-lang', newLang)
  }

  const t = (key: keyof typeof translations['th']) => {
    const dict = translations[lang] as Record<string, string>
    const fallback = translations.th as Record<string, string>
    return dict[key as string] || fallback[key as string] || String(key)
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
