-- AI Learning Quests: gamified practice assignments generated by AI
CREATE TYPE quest_difficulty AS ENUM ('easy', 'medium', 'hard', 'expert');
CREATE TYPE quest_status AS ENUM ('active', 'locked', 'archived');

-- Quests created by teacher / AI
CREATE TABLE learning_quests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id UUID NOT NULL REFERENCES users(id),
    title TEXT NOT NULL,
    topic TEXT NOT NULL,
    description TEXT,
    difficulty quest_difficulty NOT NULL DEFAULT 'easy',
    question TEXT NOT NULL,
    answer TEXT,
    hints TEXT[] DEFAULT '{}',
    explanation TEXT,
    exp_reward INTEGER NOT NULL DEFAULT 10 CHECK (exp_reward > 0),
    time_limit_minutes INTEGER,
    status quest_status NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_learning_quests_teacher ON learning_quests(teacher_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_learning_quests_status ON learning_quests(status) WHERE deleted_at IS NULL;
CREATE INDEX idx_learning_quests_difficulty ON learning_quests(difficulty) WHERE deleted_at IS NULL;

-- Student attempts (one per quest per student)
CREATE TABLE quest_attempts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    quest_id UUID NOT NULL REFERENCES learning_quests(id),
    student_id UUID NOT NULL REFERENCES users(id),
    answer TEXT,
    is_correct BOOLEAN,
    score INTEGER CHECK (score >= 0),
    feedback TEXT,
    exp_earned INTEGER DEFAULT 0,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(quest_id, student_id)
);

CREATE INDEX idx_quest_attempts_student ON quest_attempts(student_id);
CREATE INDEX idx_quest_attempts_quest ON quest_attempts(quest_id);

-- Demo quests seeded by AI for testing
INSERT INTO learning_quests (id, teacher_id, title, topic, description, difficulty, question, answer, hints, explanation, exp_reward, time_limit_minutes, status, created_at, updated_at)
VALUES
    ('lq000001-0001-0001-0001-000000000001', '22222222-2222-2222-2222-222222222222', 'Basic Multiplication', 'Mathematics - Multiplication', 'Practice single-digit multiplication', 'easy', 'What is 7 x 8?', '56', ARRAY['Think of 7 x 7 + 7', '5 x 8 + 2 x 8'], '7 x 8 = 56. You can break it down as (5 x 8) + (2 x 8) = 40 + 16 = 56.', 10, 5, 'active', now(), now()),
    ('lq000001-0001-0001-0001-000000000002', '22222222-2222-2222-2222-222222222222', 'Two-Digit Multiplication', 'Mathematics - Multiplication', 'Practice two-digit multiplication', 'medium', 'What is 12 x 15?', '180', ARRAY['12 x 10 = 120, then add 12 x 5', 'Use (10+2) x 15'], '12 x 15 = (10 x 15) + (2 x 15) = 150 + 30 = 180.', 25, 10, 'active', now(), now()),
    ('lq000001-0001-0001-0001-000000000003', '22222222-2222-2222-2222-222222222222', 'Three-Digit Challenge', 'Mathematics - Multiplication', 'Advanced multiplication challenge', 'hard', 'What is 123 x 45?', '5535', ARRAY['Break into 123 x 40 + 123 x 5', '100x45 + 20x45 + 3x45'], '123 x 45 = 123 x (40 + 5) = 4920 + 615 = 5535.', 50, 15, 'active', now(), now()),
    ('lq000001-0001-0001-0001-000000000004', '22222222-2222-2222-2222-222222222222', 'Newton''s First Law', 'Physics - Mechanics', 'Understanding inertia and Newton''s first law', 'easy', 'If a book is resting on a table, what forces are acting on it? Name them.', 'Gravity (downward) and Normal force (upward)', ARRAY['Think about why the book doesn''t fall through the table', 'What pushes back against gravity?'], 'The book experiences two forces: gravity pulling it downward and the normal force from the table pushing it upward. These forces are balanced, so the book remains at rest.', 15, 8, 'active', now(), now()),
    ('lq000001-0001-0001-0001-000000000005', '22222222-2222-2222-2222-222222222222', 'Force Calculation', 'Physics - Mechanics', 'Calculate net force on an object', 'medium', 'A 5kg object has forces of 20N east and 12N west acting on it. What is its acceleration?', '1.6 m/s² east', ARRAY['Find net force first: 20N - 12N', 'Then use F=ma'], 'Net force = 20N - 12N = 8N east. Using F = ma: a = F/m = 8/5 = 1.6 m/s² east.', 30, 12, 'active', now(), now());
