'use client'

import { useState } from 'react'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { Zap, Clock, BookOpen, CheckCircle, Lock, Star, ChevronRight } from 'lucide-react'
import { apiFetch } from '@/lib/http/client'
import { useQuery } from '@tanstack/react-query'
import { useCurrentUser } from '@/hooks/useCurrentUser'
import { Skeleton } from '@/components/ui/skeleton'

interface Quest {
  id: string
  title: string
  topic: string
  description: string
  difficulty: 'easy' | 'medium' | 'hard' | 'expert'
  exp_reward: number
  time_limit_minutes?: number
  is_completed?: boolean
}

const difficultyConfig = {
  easy: { label: 'Easy', color: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/20', stars: 1 },
  medium: { label: 'Medium', color: 'bg-amber-500/20 text-amber-400 border-amber-500/20', stars: 2 },
  hard: { label: 'Hard', color: 'bg-orange-500/20 text-orange-400 border-orange-500/20', stars: 3 },
  expert: { label: 'Expert', color: 'bg-red-500/20 text-red-400 border-red-500/20', stars: 4 },
}

function useQuests() {
  return useQuery({
    queryKey: ['learning-quests'],
    queryFn: async () => {
      const res = await apiFetch<{ data: Quest[] }>('/api/v1/quests')
      return res.data
    },
  })
}

export default function StudentQuestsPage() {
  const { user } = useCurrentUser()
  const { data: quests, isLoading } = useQuests()
  const [filter, setFilter] = useState<string>('all')

  const filtered = quests?.filter((q) => {
    if (filter === 'all') return true
    return q.difficulty === filter
  })

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white">Learning Quests</h1>
          <p className="mt-1 text-sm text-slate-400">Practice quests generated by AI. Complete them to earn EXP and level up!</p>
        </div>
        <div className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2">
          <Zap className="h-4 w-4 text-violet-400" />
          <span className="text-sm font-semibold text-white">{(user as any)?.xp ?? 0} XP</span>
          <span className="text-xs text-slate-400">Lv.{(user as any)?.level ?? 1}</span>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-2">
        {[
          { key: 'all', label: 'All' },
          { key: 'easy', label: 'Easy' },
          { key: 'medium', label: 'Medium' },
          { key: 'hard', label: 'Hard' },
          { key: 'expert', label: 'Expert' },
        ].map((f) => (
          <button
            key={f.key}
            onClick={() => setFilter(f.key)}
            className={`rounded-full px-3 py-1 text-xs font-medium transition-all ${
              filter === f.key
                ? 'bg-white/15 text-white'
                : 'border border-white/10 bg-white/5 text-slate-400 hover:bg-white/10'
            }`}
          >
            {f.label}
          </button>
        ))}
      </div>

      {/* Quest Grid */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {isLoading &&
          Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className="h-48 w-full rounded-xl bg-white/5" />
          ))}

        {filtered?.map((quest, idx) => {
          const diff = difficultyConfig[quest.difficulty]
          const completed = quest.is_completed
          return (
            <motion.div
              key={quest.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.05 }}
              className={`group relative overflow-hidden rounded-xl border p-4 transition-all duration-300 hover:scale-[1.02] ${
                completed
                  ? 'border-emerald-500/20 bg-emerald-500/5'
                  : 'border-white/10 bg-white/5 hover:bg-white/[0.07]'
              }`}
            >
              {/* Difficulty Badge */}
              <div className="flex items-center justify-between">
                <span className={`rounded-full border px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wider ${diff.color}`}>
                  {diff.label}
                </span>
                <div className="flex items-center gap-0.5">
                  {Array.from({ length: diff.stars }).map((_, i) => (
                    <Star key={i} className="h-3 w-3 fill-amber-400 text-amber-400" />
                  ))}
                </div>
              </div>

              {/* Content */}
              <div className="mt-3">
                <h3 className="text-sm font-semibold text-white">{quest.title}</h3>
                <p className="mt-0.5 text-xs text-slate-400">{quest.topic}</p>
                <p className="mt-2 line-clamp-2 text-xs text-slate-500">{quest.description}</p>
              </div>

              {/* Footer */}
              <div className="mt-4 flex items-center justify-between">
                <div className="flex items-center gap-3 text-xs text-slate-400">
                  <div className="flex items-center gap-1">
                    <Zap className="h-3 w-3 text-violet-400" />
                    <span className="font-semibold text-violet-300">+{quest.exp_reward}</span>
                  </div>
                  {quest.time_limit_minutes && (
                    <div className="flex items-center gap-1">
                      <Clock className="h-3 w-3" />
                      <span>{quest.time_limit_minutes}m</span>
                    </div>
                  )}
                </div>
                <Link
                  href={`/student/quests/${quest.id}`}
                  className={`flex items-center gap-1 rounded-lg px-3 py-1.5 text-xs font-semibold transition-all ${
                    completed
                      ? 'bg-emerald-500/20 text-emerald-400'
                      : 'bg-gradient-to-r from-violet-500 to-indigo-600 text-white hover:from-violet-600 hover:to-indigo-700'
                  }`}
                >
                  {completed ? (
                    <>
                      <CheckCircle className="h-3 w-3" />
                      Done
                    </>
                  ) : (
                    <>
                      Start
                      <ChevronRight className="h-3 w-3" />
                    </>
                  )}
                </Link>
              </div>

              {/* Completed overlay */}
              {completed && (
                <div className="absolute inset-0 flex items-center justify-center bg-slate-950/60 backdrop-blur-[1px]">
                  <div className="flex items-center gap-2 rounded-full bg-emerald-500/20 px-4 py-2 text-emerald-400">
                    <CheckCircle className="h-4 w-4" />
                    <span className="text-sm font-semibold">Completed</span>
                  </div>
                </div>
              )}
            </motion.div>
          )
        })}

        {!isLoading && (!filtered || filtered.length === 0) && (
          <div className="col-span-full rounded-xl border border-white/10 bg-white/5 p-8 text-center">
            <BookOpen className="mx-auto h-8 w-8 text-slate-600" />
            <p className="mt-2 text-sm text-slate-400">No quests available yet</p>
            <p className="text-xs text-slate-500">Your teacher will add quests soon!</p>
          </div>
        )}
      </div>
    </div>
  )
}
